services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3001:3001
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - APP_PORT=3001
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:12.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tech-challenge-order-db
    ports:
      - 5432:5432

networks:
  default:
    name: tech-challenge-order-network
