apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-order-general-settings
data:
  NODE_ENV: "development"
  APP_NAME: "tech-challenge-order"
  APP_PORT: "3001"
  APP_VERSION: "1.0.0"
  APP_DOCUMENTATION_ENDPOINT: "docs"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "${{ secrets.POSTGRES_HOST }}"
  USER_TOKEN_EXPIRES_IN: "900"
